### PR TITLE
fix name Celcius to Celsius

### PR DESCRIPTION
**Pull request by twocolors**
in www.bipm.org name metric (temperature) Celsius

### CODE REVIEW

**Comment by reneklootwijk** [comment]
Sorry for the late response, I will change this in the next update. I am working on a complete overhaul.

**Comment by twocolors** [comment]
@reneklootwijk Can you tell me when to update?

**Comment by reneklootwijk** [comment]
Currently I am testing the code to directly communicate with the original SK103 dongle without dependency on the cloud. When the code runs stable and I cleaned it up a bit I will release the new version. Note, in the new version I will drop support for the cloud communication method.

**Comment by reneklootwijk** [comment]
Done

**Pull request closed without merging**
